-- @service: hub
-- Step 1a. The hub owns the reference data. One publication, everything in it.
CREATE TABLE plans (
  plan_id int PRIMARY KEY,
  name    text NOT NULL
);
CREATE TABLE prices (
  plan_id    int REFERENCES plans,
  meter      text,
  unit_price numeric(10,4) NOT NULL,
  PRIMARY KEY (plan_id, meter)
);
CREATE TABLE customers (
  customer_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL,
  worker_id     int NOT NULL,          -- which worker takes this customer's traffic
  plan_id       int NOT NULL REFERENCES plans,
  billing_notes text                   -- billing-only: workers have no business seeing it
);

INSERT INTO plans VALUES (1, 'basic'), (2, 'pro'), (3, 'enterprise');
INSERT INTO prices VALUES
  (1, 'api_calls', 0.0100), (1, 'storage_gb', 0.5000),
  (2, 'api_calls', 0.0080), (2, 'storage_gb', 0.4000),
  (3, 'api_calls', 0.0050), (3, 'storage_gb', 0.2500);
-- nine customers, three per worker
INSERT INTO customers (name, worker_id, plan_id, billing_notes)
SELECT 'customer-' || n, (n - 1) / 3 + 1, (n - 1) % 3 + 1, 'net-30, secret discount ' || n
FROM generate_series(1, 9) n;

CREATE PUBLICATION ref_all FOR TABLE plans, prices, customers;

SELECT pubname, tablename FROM pg_publication_tables ORDER BY 1, 2;
