-- @service: worker1 worker2 worker3
-- Step 1b. Each worker creates the same tables (DDL is not replicated) and subscribes.
CREATE TABLE plans (
  plan_id int PRIMARY KEY,
  name    text NOT NULL
);
CREATE TABLE prices (
  plan_id    int,
  meter      text,
  unit_price numeric(10,4) NOT NULL,
  PRIMARY KEY (plan_id, meter)
);
CREATE TABLE customers (
  customer_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL,
  worker_id     int NOT NULL,
  plan_id       int NOT NULL,
  billing_notes text
);

-- The subscription name is also the slot name on the hub: it must be unique per worker.
CREATE SUBSCRIPTION sub_ref_w:worker_id
  CONNECTION 'host=hub dbname=app user=postgres'
  PUBLICATION ref_all;

-- wait for the initial table synchronisation (state 'r' = ready) of all three tables
SELECT lr.wait_for($$SELECT count(*) = 3 FROM pg_subscription_rel WHERE srsubstate = 'r'$$);

-- with ref_all the worker sees everything: all 9 customers, and the billing notes too
SELECT count(*) AS customers_seen, count(billing_notes) AS with_billing_notes FROM customers;
SELECT customer_id, name, worker_id, billing_notes FROM customers ORDER BY 1 LIMIT 4;
