-- @service: worker4
-- @start: worker4
-- Step 4b. The new node (empty server): schema, reference subscription (initial copy of its
-- slice only), local events for its customers, publication of the events.
CREATE TABLE plans (plan_id int PRIMARY KEY, name text NOT NULL);
CREATE TABLE prices (plan_id int, meter text, unit_price numeric(10,4) NOT NULL, PRIMARY KEY (plan_id, meter));
CREATE TABLE customers (
  customer_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL, worker_id int NOT NULL, plan_id int NOT NULL
);
CREATE SUBSCRIPTION sub_ref_w4
  CONNECTION 'host=hub dbname=app user=postgres' PUBLICATION ref_w4;
SELECT lr.wait_for($$SELECT count(*) = 3 FROM pg_subscription_rel WHERE srsubstate = 'r'$$);
SELECT customer_id, name, worker_id FROM customers ORDER BY 1;

CREATE TABLE usage_events (
  worker_id   int    NOT NULL DEFAULT :worker_id CHECK (worker_id = :worker_id),
  event_id    bigint GENERATED ALWAYS AS IDENTITY,
  customer_id int    NOT NULL,
  meter       text   NOT NULL,
  qty         int    NOT NULL,
  PRIMARY KEY (worker_id, event_id)
);
CREATE TABLE usage_naive (
  event_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, customer_id int NOT NULL, qty int NOT NULL);
INSERT INTO usage_events (customer_id, meter, qty)
SELECT customer_id, m, customer_id * 10
FROM customers, (VALUES ('api_calls'), ('storage_gb')) v(m) ORDER BY customer_id, m;
CREATE PUBLICATION pub_usage FOR TABLE usage_events;
SELECT count(*) AS local_events FROM usage_events;
