-- @service: pghub
-- Step 7a (pglogical 2.4.8 on PostgreSQL 14). Hub: node, reference tables, one replication set
-- per worker holding the tables with a row_filter and a column list.
CREATE EXTENSION pglogical;
SELECT pglogical.create_node(node_name := 'hub', dsn := 'host=pghub dbname=app user=postgres');

CREATE TABLE plans (plan_id int PRIMARY KEY, name text NOT NULL);
CREATE TABLE prices (plan_id int REFERENCES plans, meter text, unit_price numeric(10,4) NOT NULL, PRIMARY KEY (plan_id, meter));
CREATE TABLE customers (
  customer_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL,
  worker_id     int NOT NULL,
  plan_id       int NOT NULL REFERENCES plans,
  billing_notes text
);
INSERT INTO plans VALUES (1, 'basic'), (2, 'pro'), (3, 'enterprise');
INSERT INTO prices VALUES (1, 'api_calls', 0.0100), (1, 'storage_gb', 0.5000),
  (2, 'api_calls', 0.0080), (2, 'storage_gb', 0.4000), (3, 'api_calls', 0.0050), (3, 'storage_gb', 0.2500);
INSERT INTO customers (name, worker_id, plan_id, billing_notes)
SELECT 'customer-' || n, (n - 1) / 3 + 1, (n - 1) % 3 + 1, 'secret ' || n FROM generate_series(1, 6) n;

-- one replication set per worker; the filter and the columns live on the set membership
SELECT pglogical.create_replication_set('ref_w' || n) FROM generate_series(1, 2) n;
SELECT pglogical.replication_set_add_table('ref_w' || n, 'plans') FROM generate_series(1, 2) n;
SELECT pglogical.replication_set_add_table('ref_w' || n, 'prices') FROM generate_series(1, 2) n;
SELECT pglogical.replication_set_add_table(
         set_name := 'ref_w' || n, relation := 'customers', synchronize_data := false,
         columns := ARRAY['customer_id', 'name', 'worker_id', 'plan_id'],
         row_filter := 'worker_id = ' || n)
FROM generate_series(1, 2) n;
SELECT s.set_name, t.set_reloid::regclass AS tbl, t.set_att_list, t.set_row_filter
FROM pglogical.replication_set_table t JOIN pglogical.replication_set s USING (set_id)
WHERE t.set_reloid = 'customers'::regclass ORDER BY 1;
