-- @service: pgw1 pgw2
-- Step 7b. Workers: node, tables, subscription to their replication set; and their local
-- usage_events table, published through a replication set called 'usage'.
CREATE EXTENSION pglogical;
SELECT pglogical.create_node(node_name := 'worker' || :worker_id, dsn := 'host=pgw' || :worker_id || ' dbname=app user=postgres');

CREATE TABLE plans (plan_id int PRIMARY KEY, name text NOT NULL);
CREATE TABLE prices (plan_id int, meter text, unit_price numeric(10,4) NOT NULL, PRIMARY KEY (plan_id, meter));
CREATE TABLE customers (customer_id int PRIMARY KEY, name text NOT NULL, worker_id int NOT NULL, plan_id int NOT NULL);

SELECT pglogical.create_subscription(
  subscription_name := 'sub_ref_w' || :worker_id,   -- unique per provider: it is part of the slot name
  provider_dsn := 'host=pghub dbname=app user=postgres',
  replication_sets := ARRAY['ref_w' || :worker_id],
  synchronize_data := true,
  forward_origins := '{}') IS NOT NULL AS created;
SELECT pglogical.wait_for_subscription_sync_complete('sub_ref_w' || :worker_id);
SELECT customer_id, name, worker_id FROM customers ORDER BY 1;

-- Named per worker: pglogical maps tables by name, and the hub side is one partition per
-- worker (see 72 and the note on partitioned targets in the README).
CREATE TABLE usage_events_w:worker_id (
  worker_id   int    NOT NULL DEFAULT :worker_id CHECK (worker_id = :worker_id),
  event_id    bigint GENERATED BY DEFAULT AS IDENTITY,
  customer_id int    NOT NULL,
  meter       text   NOT NULL,
  qty         int    NOT NULL,
  PRIMARY KEY (worker_id, event_id)
);
INSERT INTO usage_events_w:worker_id (customer_id, meter, qty)
SELECT customer_id, m, customer_id * 10 FROM customers, (VALUES ('api_calls'), ('storage_gb')) v(m) ORDER BY 1, 2;
SELECT pglogical.create_replication_set('usage');
SELECT pglogical.replication_set_add_table('usage', 'usage_events_w' || :worker_id);
