baseURL = "http://tapoueh.org/"
languageCode = "en-us"
title = "Dimitri Fontaine, PostgreSQL Expert"
theme = "tranquilpeak"
publishDir = "docs"

googleAnalytics = "UA-47059482-1"
disqusShortname = "tapoueh"

[permalinks]
  post = "/blog/:year/:month/:slug/"
  page = "/:filename/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Dimitri Fontaine"
  bio = "PostgreSQL Major Contributor"
  job = "Open Source Software Engineer"
  location = "France"
  gravatarEmail = "dim@tapoueh.org"
  twitter = "tapoueh"
  googlePlus = "+DimitriFontaine"

[[menu.main]]
  weight = 1
  identifier = "blog"
  name = "Blog"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-pagelines\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-beer\"></i>"
  url = "/about/"
[[menu.main]]
  weight = 3
  identifier = "book"
  name = "Book"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-book\"></i>"
  url = "/book/"
# [[menu.main]]
#   weight = 4
#   identifier = "confs"
#   name = "Conferences"
#   pre = "<i class=\"sidebar-button-icon fa fa-lg fa-plane\"></i>"
#   url = "/tags/conferences/"
# [[menu.main]]
#   weight = 5
#   identifier = "projects"
#   name = "Projects"
#   pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bug\"></i>"
#   url = "/projects/"
  
[[menu.links]]
  weight = 6
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
  url = "/categories"
# [[menu.links]]
#   weight = 7
#   identifier = "tags"
#   name = "Tags"
#   pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
#   url = "/tags"
# [[menu.links]]
#   weight = 8
#   identifier = "archives"
#   name = "Archives"
#   pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
#   url = "/archives"

[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/dimitri"

[[menu.links]]
  weight = 2
  identifier = "twitter"
  name = "Twitter"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-twitter\"></i>"
  url = "https://twitter.com/tapoueh"

[[menu.misc]]
  weight = 10
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
  url = "/index.xml"


[params]
  dateFormat = "Monday 02 Jan 2006"
  clearReading = false
  hierarchicalCategories = true
  sidebarBehavior = 2
  coverImage = "Tree_Of_Light_by_lowapproach.jpg"
  thumbnailImage = true
  thumbnailImagePosition = "left"
  favicon = "/favicon.ico"
  customCSS = ["/css/dim.css"]

