baseURL = "https://tapoueh.org/"
languageCode = "en-us"
title = "The Art of PostgreSQL"
theme = "tranquilpeak"
publishDir = "docs"

googleAnalytics = "UA-47059482-1"
disqusShortname = "tapoueh"

PygmentsCodeFences = true
pygmentsstyle = "autumn"

[permalinks]
  post = "/blog/:year/:month/:slug/"
  page = "/:filename/"
  conf = "/conf/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Dimitri Fontaine"
  bio = "PostgreSQL Major Contributor"
  job = "Open Source Software Engineer"
  location = "France"
  gravatarEmail = "dim@tapoueh.org"
  twitter = "tapoueh"
  googlePlus = "+DimitriFontaine"

[[menu.main]]
  weight = 1
  identifier = "blog"
  name = "Blog"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-pagelines\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-beer\"></i>"
  url = "/about/"
[[menu.main]]
  weight = 3
  identifier = "yesql"
  name = "YeSQL"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-database\"></i>"
  url = "/categories/yesql/"
[[menu.main]]
  weight = 4
  identifier = "book"
  name = "Mastering PostgreSQL"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-book\"></i>"
  #url = "/book/"
  url = "http://masteringpostgresql.com"
[[menu.links]]
  weight = 6
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
  url = "/categories"

[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/dimitri"
[[menu.links]]
  weight = 2
  identifier = "twitter"
  name = "Twitter"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-twitter\"></i>"
  url = "https://twitter.com/tapoueh"

[[menu.misc]]
  weight = 10
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
  url = "/index.xml"


[params]
  dateFormat = "Monday 02 Jan 2006"
  clearReading = false
  hierarchicalCategories = true
  sidebarBehavior = 5
  #coverImage = "Tree_Of_Light_by_lowapproach.jpg"
  #coverImage = "/img/elephant-herd-shadow-falls.jpg"
  coverImage = "mayan-calendar.jpg"
  thumbnailImage = true
  thumbnailImagePosition = "left"
  favicon = "/favicon.ico"
  customCSS = ["css/dim.css", "css/nav.css"]
  syntaxHighlighter = "highlight.js"

  [params.header.rightLink]
    icon = "book"
    logo = "/img/logo.png"
    url = "https://theartofpostgresql.com/"

#
# Attempt at a top
#
[[menu.top]]
    name = "blog"
    url  = "/"
    weight = 1
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"

[[menu.top]]
    name = "talks"
    url  = "/conf/"
    weight = 2
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-microphone\"></i>"

[[menu.top]]
    name = "Twitter"
    url  = "https://twitter.com/tapoueh"
    weight = 3
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-twitter\"></i>"

# [[menu.top]]
#     name = "Mastering PostgreSQL"
#     url  = "https://masteringpostgresql.com/"
#     weight = 4
#     pre = "<i class=\"sidebar-button-icon fa fa-lg fa-book\"></i>"

[[menu.top]]
    name = "The Art Of PostgreSQL"
    url  = "http://theartofpostgresql.com"
    weight = 4
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-book\"></i>"

# [[menu.top]]
#     name = "Github"
#     url  = "https://github.com/dimitri"
#     weight = 4
#     pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"

# [[menu.top]]
#     name = "Google+"
#     url  = "https://plus.google.com/+DimitriFontaine"
#     weight = 6
#     pre = "<i class=\"sidebar-button-icon fa fa-lg fa-google-plus\"></i>"

# [[menu.top]]
#     name = "LinkedIn"
#     url  = "https://www.linkedin.com/in/dimitrifontaine/"
#     weight = 7
#     pre = "<i class=\"sidebar-button-icon fa fa-lg fa-linkedin\"></i>"

# [[menu.top]]
#     name = "pgloader"
#     url  = "http://pgloader.io/"
#     weight = 8
#     pre = "<i class=\"sidebar-button-icon fa fa-lg fa-truck\"></i>"
