What to write about next?

* PostgreSQL
** Setting up pgloader
** pgfincore debian's packaging
** skytools 3
** writing an extension in SQL
** what problems do we solve with extensions

* PostgreSQL Fr
** Configurer pgloader
** Choisir sa réplication PostgreSQL
** Nouvelles série : découvertes 
*** Découvrir Skytools
*** Découvrir PGQ
*** Découvrir Hot Standby et ses réplications
*** Découvrir plproxy
*** Découvrir pgbouncer
*** Réplication Synchrone : quand, pourquoi ?
** Réplications PostgreSQL : un exemple concret
   Exemple d'utilisation de toutes les technos dans un même projet,
   suffisemment complexe.  Trouver un exemple sympa.
*** PRA
*** Séparation des responsabilités
*** Reporting consolidé
*** avec Vues Matérialisées (plproxy)
** Les nouveautés de PostgreSQL 9.1
*** Extensions
*** SSI
*** Réplication Synchrone
*** AND?
** PostgreSQL, le plein de fonctionnalité
*** Comprendre les tableaux
*** Comprendre les contribs
*** Comprendre le catalogue système
*** Comprendre les “window functions”
*** Comprendre les CTE
*** Comprendre EXPLAIN ANALYZE
** Planifier ses backups

* Emacs
** bitlbee 3.0 and ForkDaemon mode
** Setup Gnus for inlining scaled down images in mails
** Fix term color vector!    
    (when-running-debian-or-ubuntu
     ;; we are still using the default colors elsewhere
     (require 'ansi-color)
     (setq ansi-color-names-vector
           (vector (frame-parameter nil 'background-color)
    	       "#f57900" "#8ae234" "#edd400" "#729fcf"
    	       "#ad7fa8" "cyan3" "#eeeeec")
           ansi-term-color-vector ansi-color-names-vector
           ansi-color-map (ansi-color-make-color-map)))   
** Startup done notification
    (defun dim:notify-startup-done ()
      " notify user that Emacs is now ready"
      (el-get-notify
       "Emacs is ready."
       (format "The init sequence took %g seconds."
    	   (float-time (time-subtract after-init-time before-init-time)))))
    
    (add-hook 'after-init-hook 'dim:notify-startup-done)

