-- @service: old
-- @db: postgres
-- Step 10: the "legacy" PostgreSQL 16 server gets roles, an application schema
-- exercising every awkward case, and enough data to make the initial sync take
-- a few seconds.
\set ON_ERROR_STOP on
SELECT version();

CREATE ROLE app       LOGIN PASSWORD 'app';
CREATE ROLE reporting LOGIN PASSWORD 'reporting';
CREATE ROLE repl      LOGIN REPLICATION PASSWORD 'repl';
GRANT pg_read_all_data TO repl;          -- lets the initial COPY read every table
CREATE DATABASE app OWNER app;
\c app

SET ROLE app;

-- (1) identity column + unique key, and the parent side of a foreign key
CREATE TABLE customers (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email      text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- (2) a standalone sequence (not owned by any column) used through a DEFAULT
CREATE SEQUENCE invoice_no START 1000;

-- (3) serial PK, foreign key, stored generated column, standalone sequence
CREATE TABLE orders (
  id          bigserial PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers (id),
  amount      numeric(10,2) NOT NULL,
  vat         numeric(10,2) GENERATED ALWAYS AS (round(amount * 0.20, 2)) STORED,
  invoice     bigint NOT NULL DEFAULT nextval('invoice_no'),
  client_seq  bigint,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX orders_client_seq_idx ON orders (client_seq);

-- (4) NO primary key, no unique index: the replica identity problem
CREATE TABLE audit_log (
  at      timestamptz NOT NULL DEFAULT now(),
  event   text NOT NULL,
  payload text
);

CREATE TABLE counters (name text PRIMARY KEY, n bigint NOT NULL);

-- rows written by the cutover procedure to prove the other side has caught up
CREATE TABLE cutover_markers (id text PRIMARY KEY, at timestamptz NOT NULL DEFAULT now());

-- (5) partitioned table (range + default partition), identity column
CREATE TABLE measurements (
  id     bigint GENERATED BY DEFAULT AS IDENTITY,
  ts     timestamptz NOT NULL,
  sensor int NOT NULL,
  value  float8 NOT NULL,
  PRIMARY KEY (id, ts)
) PARTITION BY RANGE (ts);
CREATE TABLE measurements_2026  PARTITION OF measurements
  FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');
CREATE TABLE measurements_other PARTITION OF measurements DEFAULT;

-- (6) a large object referenced from a table
CREATE TABLE documents (id int PRIMARY KEY, title text, body_oid oid);

-- data
INSERT INTO customers (email)
  SELECT 'seed' || g || '@example.com' FROM generate_series(1, 50000) g;
INSERT INTO orders (customer_id, amount, client_seq)
  SELECT 1 + (g % 50000), (g % 500) + 0.99, -g FROM generate_series(1, 600000) g;
INSERT INTO audit_log (event, payload)
  SELECT 'seed', 'row ' || g FROM generate_series(1, 100000) g;
INSERT INTO counters VALUES ('orders', 0);
INSERT INTO measurements (ts, sensor, value)
  SELECT now() - (g || ' seconds')::interval, g % 10, random()
    FROM generate_series(1, 300000) g;
INSERT INTO documents VALUES
  (1, 'manual', lo_from_bytea(0, convert_to(repeat('lorem ipsum ', 5000), 'UTF8')));

-- (7) a materialized view
CREATE MATERIALIZED VIEW sales_by_day AS
  SELECT date_trunc('day', created_at) AS day, count(*) AS orders, sum(amount) AS total
    FROM orders GROUP BY 1;
CREATE UNIQUE INDEX ON sales_by_day (day);

RESET ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO reporting;
ANALYZE;

\dt+
\ds
SELECT count(*) AS large_objects FROM pg_largeobject_metadata;
